import numpy as np

dictionary = {
    "config": {
        "inference": {
            "input_pdb": "outputs/test_p6x0d/input.pdb",
            "num_designs": 1,
            "design_startnum": 0,
            "ckpt_override_path": None,
            "symmetry": None,
            "recenter": True,
            "radius": 10.0,
            "model_only_neighbors": False,
            "output_prefix": "outputs/test_p6x0d",
            "write_trajectory": True,
            "scaffold_guided": False,
            "model_runner": "SelfConditioning",
            "cautious": True,
            "align_motif": True,
            "symmetric_self_cond": True,
            "final_step": 1,
            "deterministic": False,
            "trb_save_ckpt_path": "/content/RFdiffusion/inference/../models/Base_ckpt.pt",
            "dump_pdb": True,
            "dump_pdb_path": "/dev/shm",
        },
        "contigmap": {
            "contigs": ["A117-125/13-13/A107-114/13-13/A47-53/19-19/A60-65"],
            "inpaint_seq": None,
            "provide_seq": None,
            "length": None,
        },
        "model": {
            "n_extra_block": 4,
            "n_main_block": 32,
            "n_ref_block": 4,
            "d_msa": 256,
            "d_msa_full": 64,
            "d_pair": 128,
            "d_templ": 64,
            "n_head_msa": 8,
            "n_head_pair": 4,
            "n_head_templ": 4,
            "d_hidden": 32,
            "d_hidden_templ": 32,
            "p_drop": 0.15,
            "SE3_param_full": {
                "num_layers": 1,
                "num_channels": 32,
                "num_degrees": 2,
                "n_heads": 4,
                "div": 4,
                "l0_in_features": 8,
                "l0_out_features": 8,
                "l1_in_features": 3,
                "l1_out_features": 2,
                "num_edge_features": 32,
            },
            "SE3_param_topk": {
                "num_layers": 1,
                "num_channels": 32,
                "num_degrees": 2,
                "n_heads": 4,
                "div": 4,
                "l0_in_features": 64,
                "l0_out_features": 64,
                "l1_in_features": 3,
                "l1_out_features": 2,
                "num_edge_features": 64,
            },
            "d_time_emb": 0,
            "d_time_emb_proj": 10,
            "freeze_track_motif": False,
            "use_motif_timestep": True,
        },
        "diffuser": {
            "T": 50,
            "b_0": 0.01,
            "b_T": 0.07,
            "schedule_type": "linear",
            "so3_type": "igso3",
            "crd_scale": 0.25,
            "partial_T": None,
            "so3_schedule_type": "linear",
            "min_b": 1.5,
            "max_b": 2.5,
            "min_sigma": 0.02,
            "max_sigma": 1.5,
        },
        "denoiser": {
            "noise_scale_ca": 1,
            "final_noise_scale_ca": 1,
            "ca_noise_schedule_type": "constant",
            "noise_scale_frame": 1,
            "final_noise_scale_frame": 1,
            "frame_noise_schedule_type": "constant",
        },
        "ppi": {"hotspot_res": None},
        "potentials": {
            "guiding_potentials": None,
            "guide_scale": 10,
            "guide_decay": "constant",
            "olig_inter_all": None,
            "olig_intra_all": None,
            "olig_custom_contact": None,
            "substrate": None,
        },
        "contig_settings": {"ref_idx": None, "hal_idx": None, "idx_rf": None, "inpaint_seq_tensor": None},
        "preprocess": {
            "sidechain_input": False,
            "motif_sidechain_input": True,
            "d_t1d": 22,
            "d_t2d": 44,
            "prob_self_cond": 0.5,
            "str_self_cond": True,
            "predict_previous": False,
        },
        "logging": {"inputs": False},
        "scaffoldguided": {
            "scaffoldguided": False,
            "target_pdb": False,
            "target_path": None,
            "scaffold_list": None,
            "scaffold_dir": None,
            "sampled_insertion": 0,
            "sampled_N": 0,
            "sampled_C": 0,
            "ss_mask": 0,
            "systematic": False,
            "target_ss": None,
            "target_adj": None,
            "mask_loops": True,
            "contig_crop": None,
        },
    },
    "plddt": array(
        [
            [0.8073534, 0.8678454, 0.8907927, ..., 0.90316427, 0.9249125, 0.8952496],
            [0.85271174, 0.90818906, 0.9289542, ..., 0.9602003, 0.97882926, 0.947482],
            [0.8496099, 0.903334, 0.92545956, ..., 0.9550656, 0.97505593, 0.9413242],
            ...,
            [0.9854235, 0.99658054, 0.9980692, ..., 0.9981956, 0.99830496, 0.99574924],
            [0.98656815, 0.99709237, 0.9983519, ..., 0.998486, 0.9984574, 0.9959874],
            [0.98800784, 0.99760574, 0.99861515, ..., 0.9986233, 0.998561, 0.9963816],
        ],
        dtype=float32,
    ),
    "device": "Tesla T4",
    "time": 36.46577572822571,
    "con_ref_pdb_idx": [
        ("A", np.int64(117)),
        ("A", np.int64(118)),
        ("A", np.int64(119)),
        ("A", np.int64(120)),
        ("A", np.int64(121)),
        ("A", np.int64(122)),
        ("A", np.int64(123)),
        ("A", np.int64(124)),
        ("A", np.int64(125)),
        ("A", np.int64(107)),
        ("A", np.int64(108)),
        ("A", np.int64(109)),
        ("A", np.int64(110)),
        ("A", np.int64(111)),
        ("A", np.int64(112)),
        ("A", np.int64(113)),
        ("A", np.int64(114)),
        ("A", np.int64(47)),
        ("A", np.int64(48)),
        ("A", np.int64(49)),
        ("A", np.int64(50)),
        ("A", np.int64(51)),
        ("A", np.int64(52)),
        ("A", np.int64(53)),
        ("A", np.int64(60)),
        ("A", np.int64(61)),
        ("A", np.int64(62)),
        ("A", np.int64(63)),
        ("A", np.int64(64)),
        ("A", np.int64(65)),
    ],
    "con_hal_pdb_idx": [
        ("A", np.int64(1)),
        ("A", np.int64(2)),
        ("A", np.int64(3)),
        ("A", np.int64(4)),
        ("A", np.int64(5)),
        ("A", np.int64(6)),
        ("A", np.int64(7)),
        ("A", np.int64(8)),
        ("A", np.int64(9)),
        ("A", np.int64(23)),
        ("A", np.int64(24)),
        ("A", np.int64(25)),
        ("A", np.int64(26)),
        ("A", np.int64(27)),
        ("A", np.int64(28)),
        ("A", np.int64(29)),
        ("A", np.int64(30)),
        ("A", np.int64(44)),
        ("A", np.int64(45)),
        ("A", np.int64(46)),
        ("A", np.int64(47)),
        ("A", np.int64(48)),
        ("A", np.int64(49)),
        ("A", np.int64(50)),
        ("A", np.int64(70)),
        ("A", np.int64(71)),
        ("A", np.int64(72)),
        ("A", np.int64(73)),
        ("A", np.int64(74)),
        ("A", np.int64(75)),
    ],
    "con_ref_idx0": array(
        [
            97,
            98,
            99,
            100,
            101,
            102,
            103,
            104,
            105,
            87,
            88,
            89,
            90,
            91,
            92,
            93,
            94,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            40,
            41,
            42,
            43,
            44,
            45,
        ]
    ),
    "con_hal_idx0": array(
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 23, 24, 25, 26, 27, 28, 29, 43, 44, 45, 46, 47, 48, 49, 69, 70, 71, 72, 73, 74]
    ),
    "inpaint_str": array(
        [
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            True,
            True,
            True,
            True,
            True,
            True,
        ]
    ),
    "inpaint_seq": array(
        [
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            False,
            True,
            True,
            True,
            True,
            True,
            True,
        ]
    ),
    "sampled_mask": ["A117-125/13-13/A107-114/13-13/A47-53/19-19/A60-65"],
    "mask_1d": [
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        True,
        True,
        True,
        True,
        True,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        True,
        True,
        True,
        True,
        True,
        True,
    ],
}
